# Permalinks
permalink: pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Quizlet app rethink
tagline:          'Formation Prototype'
url:              http://quizlet.github.io/formation-prototype/
baseurl:          /formation-prototype/
